In [1]:
#mount to drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#read csv from drive path
import pandas as pd
path = '/content/drive/MyDrive/ERP Rijksmuseum /rijks_17th_paintings_metadata_raw.csv'
dataunfiltered = pd.read_csv(path)

In [3]:
dataunfiltered.head()

,id,objectNumber,title_en,title_nl,principal_maker,date_begin,date_end,description,materials,techniques,...,derived_image_url,height_cm,width_cm,last_modified_summary,provenance_note,signature_note,classified_as,equivalent_hdl,member_of_sets,is_likely_dutch
0,https://id.rijksmuseum.nl/200107757,SK-A-4013,Portrait of Govert van Slingelandt (1623-1690)...,"Portret Govert van Slingelandt (1623-90), zijn...",Jan Mijtens,1657-01-01T00:00:00Z,1657-12-31T23:59:59Z,"Familieportret van Govert van Slingelandt, hee...","22010, 2209",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_A_...,—,—,"1991-1991: an old retouching removed, filled a...",<div><p>? Commissioned by the sitters; ? their...,"signatuur en datum, rechtsonder: ‘Joan: Mijten...",2208,http://hdl.handle.net/10934/RM0001.COLLECT.4553,"260238, 260251, 260241, 26121, 261208, 260239",True
1,https://id.rijksmuseum.nl/200107770,SK-A-276,"Een herderin, bekend als 'De schone herderin'","A Shepherdess, known as ‘The beautiful Shepher...",Paulus Moreelse,1630-01-01T00:00:00Z,1630-12-31T23:59:59Z,"…; collection Bernardus Ocke (c. 1755-1816), L...","2209, 22010",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_A_...,—,—,1968-1968: retouched… | 1979-1979: complete re...,—,"signatuur en datum, rechtsboven, met monogram:...",2208,http://hdl.handle.net/10934/RM0001.COLLECT.4645,"260239, 261208, 260212, 260251, 26121, 260238",True
2,https://id.rijksmuseum.nl/200107771,SK-C-1440,"Portrait of a Man, possibly Reijnier Pauw (159...","Portret van een man, mogelijk Reijnier Pauw (1...",Paulus Moreelse,1625-01-01T00:00:00Z,1625-12-31T23:59:59Z,…; ? through the family of the sitter to Maart...,"220116, 2209",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_C_...,—,—,1972-1972: complete restoration…,—,"signatuur en datum, linksboven met monogram: ‘...",2208,http://hdl.handle.net/10934/RM0001.COLLECT.4647,"260251, 26121, 260239, 260212, 260241, 261208,...",True
3,https://id.rijksmuseum.nl/200107776,SK-C-1215,"Portrait of Thomas Hees (b. 1634/35), resident...",Thomas Hees en zijn bediende Thomas en neven J...,—,1687-01-01T00:00:00Z,1687-12-31T23:59:59Z,"Portretten van Thomas Hees, resident en commis...","2209, 22010",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_C_...,—,—,—,—,signature and date: ‘Michiel van Musscher Pinx...,2208,http://hdl.handle.net/10934/RM0001.COLLECT.4675,"260241, 261208, 260212, 260251, 260238, 260246...",True
4,https://id.rijksmuseum.nl/200107777,SK-A-4232,Self-Portrait,Zelfportret,—,1685-01-01T00:00:00Z,1685-12-31T23:59:59Z,"inscriptie, onderaan: ‘Dus heeft hier Muschers...","22010, 2209",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_A_...,—,—,—,—,—,2208,http://hdl.handle.net/10934/RM0001.COLLECT.4676,"261208, 260239, 260251, 260238",True

In [18]:
#filter for the words 'interior' or 'interieur' in the dataframe
filtered_data = dataunfiltered[dataunfiltered['description'].str.contains('interieur|interior|room|voorhuis|kamer|kitchen|keuken', na=False) |
                             dataunfiltered['title_nl'].str.contains('interieur|interior|room|voorhuis|kamer|kitchen|keuken', na=False) |
                             dataunfiltered['title_en'].str.contains('interieur|interior|room|voorhuis|kamer|kitchen|keuken', na=False)]
filtered_data.head()

,id,objectNumber,title_en,title_nl,principal_maker,date_begin,date_end,description,materials,techniques,...,derived_image_url,height_cm,width_cm,last_modified_summary,provenance_note,signature_note,classified_as,equivalent_hdl,member_of_sets,is_likely_dutch
9,https://id.rijksmuseum.nl/200107821,SK-C-200,Boerengezelschap binnenshuis,Peasants in an Interior,—,1661-01-01T00:00:00Z,1661-12-31T23:59:59Z,"<div><p>...; ? probate inventory, Nicolaas Cor...","220150, 2209",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_C_...,—,—,2000-2000: complete restoration…,"<div><p>...; ? probate inventory, Nicolaas Cor...","signatuur en datum, rechtsonder: ‘Av. Ostade ....",2208,http://hdl.handle.net/10934/RM0001.COLLECT.4899,"261208, 260239, 260212, 26121, 260214, 260238,...",True
14,https://id.rijksmuseum.nl/200107873,SK-A-834,Watermill by a Wooded Outcrop,Watermolen bij een beboste heuvel,—,1633-01-01T00:00:00Z,1633-12-31T23:59:59Z,Ovaal berglandschap met een watermolen gelegen...,"220116, 2209",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_A_...,—,—,—,—,"signature and date, lower left: ‘·Gilis·Peeter...",2208,http://hdl.handle.net/10934/RM0001.COLLECT.5021,"260251, 261208, 260238, 260239, 26118",True
20,https://id.rijksmuseum.nl/200107929,SK-C-6,De Staalmeesters: het college van staalmeester...,De waardijns van het Amsterdamse lakenbereider...,—,1662-01-01T00:00:00Z,1662-12-31T23:59:59Z,Commissioned by the sitters for the hall of th...,"2209, 22010",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_C_...,—,—,—,—,signature and date (false): ‘Rembrandt. f. 166...,2208,http://hdl.handle.net/10934/RM0001.COLLECT.5217,"260214, 260251, 260239, 260212, 261208, 260241...",True
50,https://id.rijksmuseum.nl/200108176,SK-A-2539,The Man-of-War Brielle on the River Maas off R...,Het oorlogsschip Brielle op de Maas voor Rotte...,—,1689-01-01T00:00:00Z,1689-12-31T23:59:59Z,Het fregat 'Brielle' op de Maas voor Rotterdam...,"2209, 22010",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_A_...,—,—,—,—,signature and date: ‘L. Bakh. Ft 1689’…,2208,http://hdl.handle.net/10934/RM0001.COLLECT.5884,"260241, 261208, 260239, 260212, 260238, 260211...",True
89,https://id.rijksmuseum.nl/200108407,SK-A-4055,"Interior of a Protestant, Gothic Church during...","Interieur van een protestantse, gotische kerk ...",—,1669-01-01T00:00:00Z,1669-12-31T23:59:59Z,Interieur van een protestantse gotische kerk m...,"2209, 220116",2202217,...,https://lh3.googleusercontent.com/[GUID]/SK_A_...,—,—,—,"…; ? sale [seller ‘S’],{Ms note in the copy of...","signatuur en datum, rechtsboven: ‘Aº 1669 E. D...",2208,http://hdl.handle.net/10934/RM0001.COLLECT.6585,"260238, 261208, 260212, 260251, 260239",True

In [19]:
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 9 to 740
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     37 non-null     object
 1   objectNumber           37 non-null     object
 2   title_en               37 non-null     object
 3   title_nl               37 non-null     object
 4   principal_maker        37 non-null     object
 5   date_begin             37 non-null     object
 6   date_end               37 non-null     object
 7   description            37 non-null     object
 8   materials              37 non-null     object
 9   techniques             37 non-null     object
 10  direct_image_urls      37 non-null     object
 11  derived_image_url      37 non-null     object
 12  height_cm              37 non-null     object
 13  width_cm               37 non-null     object
 14  last_modified_summary  37 non-null     object
 15  provenance_note        37 non-null     object
 16  signature_note         37 non-null     object
 17  classified_as          37 non-null     object
 18  equivalent_hdl         37 non-null     object
 19  member_of_sets         37 non-null     object
 20  is_likely_dutch        37 non-null     bool
dtypes: bool(1), object(20)
memory usage: 6.1+ KB